import streamlit as st
import pandas as pd
import os


# PAGE CONFIG
st.set_page_config(
    page_title="Prediction History",
    layout="wide"
)

# CUSTOM CSS
st.markdown("""
<style>
.history-card {
    background:#020617;
    padding:20px;
    border-radius:12px;
    border:1px solid #1e293b;
    transition:0.3s;
}
.history-card:hover {
    box-shadow:0 0 15px rgba(56,189,248,0.25);
}
</style>
""", unsafe_allow_html=True)

# TITLE
st.markdown("## 📜 Prediction History")
st.caption(
    "Audit trail of all CSV uploads and prediction runs "
    "(used for monitoring, debugging, and reporting)."
)


# LOG FILE PATH
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_PATH = os.path.join(BASE_DIR, "..", "..", "logs", "history_logs.csv")


# LOAD HISTORY (FRESH EVERY TIME)
if not os.path.exists(LOG_PATH):
    st.warning("No history available yet. Upload a CSV file first.")
    st.stop()

df = pd.read_csv(LOG_PATH)

if df.empty:
    st.warning("History file exists but no records found.")
    st.stop()


# TOP METRICS

c1, c2, c3, c4 = st.columns(4)

c1.metric("Total Runs", len(df))
c2.metric("Total Flows", int(df["total_flows"].sum()))
c3.metric("Total Attacks", int(df["attack_count"].sum()))
c4.metric("Total Benign", int(df["benign_count"].sum()))



# FILTER SECTION
st.markdown("### 🔍 Filter History")

with st.expander("Apply Filters"):
    csv_filter = st.multiselect(
        "Filter by CSV file",
        options=sorted(df["csv_name"].unique())
    )

    if csv_filter:
        df = df[df["csv_name"].isin(csv_filter)]


# SELECT A RUN FOR EXPLAINABILITY
st.markdown("### 🔗 Open Explainability for a Run")

selected_index = st.selectbox(
    "Select a prediction run",
    options=df.index,
    format_func=lambda i: f"{df.loc[i, 'timestamp']} | {df.loc[i, 'csv_name']}"
)

if st.button("🧠 View Explainability for this Run"):
    st.session_state["selected_run"] = df.loc[selected_index].to_dict()
    st.switch_page("pages/4_explainability.py")


# HISTORY TABLE
st.markdown("### 🗂️ History Records")

st.dataframe(
    df.sort_values("timestamp", ascending=False),
    use_container_width=True,
    height=400
)


# VISUAL SUMMARY
st.markdown("### 📊 Visual Summary:")

v1, v2 = st.columns(2)

with v1:

    st.markdown("#### Attack vs Benign (Overall)")

    pie_df = pd.DataFrame({
        "Type": ["Benign", "Attack"],
        "Count": [
            df["benign_count"].sum(),
            df["attack_count"].sum()
        ]
    })

    st.plotly_chart(
        {
            "data": [{
                "labels": pie_df["Type"],
                "values": pie_df["Count"],
                "type": "pie",
                "hole": 0.4,
                "marker": {
                    "colors": ["green", "red"]
                }
            }],
            "layout": {
                "height": 300,
                "margin": {"t": 20, "b": 0}
            }
        },
        use_container_width=True
    )

    st.markdown('</div>', unsafe_allow_html=True)

with v2:
    
    st.markdown("#### Attacks per Run")

    bar_df = df.copy()
    bar_df["run"] = range(1, len(bar_df) + 1)

    st.plotly_chart(
        {
            "data": [{
                "x": bar_df["run"],
                "y": bar_df["attack_count"],
                "type": "bar",
                "marker": {"color": "red"}
            }],
            "layout": {
                "height": 300,
                "xaxis": {"title": "Run Number"},
                "yaxis": {"title": "Attack Count"},
                "margin": {"t": 20}
            }
        },
        use_container_width=True
    )

    st.markdown('</div>', unsafe_allow_html=True)


# DOWNLOAD
st.markdown("### ⬇️ Download History Logs")

csv_bytes = df.to_csv(index=False).encode("utf-8")

st.download_button(
    label="📥 Download History as CSV",
    data=csv_bytes,
    file_name="prediction_history.csv",
    mime="text/csv"
)


# FOOTER
st.caption(
    "History logs are automatically generated by the backend "
    "during every batch prediction run."
)
